version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.11'

python:
  install:
    - method: pip
      path: .
    - method: pip
      requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
