name: Test and Publish

on:
  release:
    types: [published]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependecies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build pytest numpy

      - name: Run numpy tests
        run: pytest tests/numpy_test.py
      
      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
